name: CI
on:  [workflow_dispatch, pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install CUDA dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            git \
            build-essential \
            libhdf5-dev \
            python3-pip \
            python3-dev \
            sudo \
            wget
          
      - name: Install PyTorch with CUDA
        run: |
          pip install torch --extra-index-url https://download.pytorch.org/whl/cu121
          
      - name: Install project dependencies
        run: |
          pip install seaborn scikit-learn umap-learn h5py matplotlib plotly pandas pytorch-lightning fastdtw papermill
          pip install wandb pytest
          pip install ipykernel jupyter nbdev
          nbdev_install_quarto
          
      - name: Install Julia
        run: |
          echo "Installing Julia..."
          wget https://julialang-s3.julialang.org/bin/linux/x64/1.10/julia-1.10.5-linux-x86_64.tar.gz
          tar -xvzf julia-1.10.5-linux-x86_64.tar.gz
          sudo mv julia-1.10.5 /opt/julia
          sudo ln -s /opt/julia/bin/julia /usr/local/bin/julia
          rm julia-1.10.5-linux-x86_64.tar.gz
          echo "Julia version:"
          julia --version
          echo "Julia path:"
          which julia
          
      - name: Set up Julia environment
        run: |
          echo "Setting up Julia environment..."
          export JULIA_DEPOT_PATH=/opt/julia_depot
          mkdir -p $JULIA_DEPOT_PATH
          echo "JULIA_DEPOT_PATH: $JULIA_DEPOT_PATH"
          
          echo "Installing Julia packages..."
          julia -e 'using Pkg; Pkg.add(["DifferentialEquations", "Polynomials", "LinearAlgebra", "MAT", "NPZ", "IJulia"])'
          
          echo "Setting up IJulia..."
          julia -e 'using IJulia; IJulia.installkernel("Julia")'
          
      - name: Install and configure PyJulia
        run: |
          echo "Installing PyJulia..."
          pip install julia
          
          echo "Setting JULIA_PYTHONCALL_EXE and PYTHON environment variables..."
          export JULIA_PYTHONCALL_EXE=$(which python)
          export PYTHON=$(which python)
          
          echo "Installing PyCall in Julia..."
          julia -e 'using Pkg; Pkg.add("PyCall"); ENV["PYTHON"]="'$(which python)'"; Pkg.build("PyCall")'
          
          echo "Initializing PyJulia..."
          python -c "import julia; julia.install()"
          
          echo "Testing PyJulia import..."
          python -c "from julia.api import Julia; print('PyJulia import successful')"
          
          echo "Testing Julia initialization..."
          python -c "from julia.api import Julia; jl = Julia(compiled_modules=False); print('Julia initialization successful')"
          
          echo "Testing Julia package import..."
          python -c "from julia import Main; print('Julia Main import successful')"
          
          echo "Testing individual Julia packages..."
          python -c "from julia.api import Julia; jl = Julia(compiled_modules=False); from julia import Main; print('Testing DifferentialEquations...'); Main.eval('println(\"DifferentialEquations package status:\"); using Pkg; Pkg.status(\"DifferentialEquations\")')"
          
          echo "Making Julia package environment accessible to PyJulia..."
          python -c "from julia.api import Julia; jl = Julia(compiled_modules=False); from julia import Main; Main.eval('println(\"Current Julia environment:\"); using Pkg; Pkg.status()')"
          
      - name: Run nbdev CI
        uses: fastai/workflows/nbdev-ci@master
