# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_constants.ipynb.

# %% auto 0
__all__ = ['MU', 'EM_POINTS', 'EM_ORBIT_TYPES']

# %% ../nbs/00_constants.ipynb 1
MU = 0.0122

# %% ../nbs/00_constants.ipynb 2
EM_POINTS={
    'Moon': (1-MU,0,0),
    'Earth': (-MU,0,0),
    'Lagrange 1': (0.8369,0,0),
    'Lagrange 2': (1.1557,0,0)
}

# %% ../nbs/00_constants.ipynb 3
EM_ORBIT_TYPES = {
    1: "S_BN",
    2: "S_BS",
    3: "S_DN",
    4: "S_DPO",
    5: "S_DRO",
    6: "S_DS",
    7: "S_L1_A",
    8: "S_L1_HN",
    9: "S_L1_HS",
    10: "S_L1_L",
    11: "S_L1_V",
    12: "S_L2_A",
    13: "S_L2_HN",
    14: "S_L2_HS",
    15: "S_L2_L",
    16: "S_L2_V",
    17: "S_L3_A",
    18: "S_L3_HN",
    19: "S_L3_HS",
    20: "S_L3_L",
    21: "S_L3_V",
    22: "S_L4_A",
    23: "S_L4_LP",
    24: "S_L4_SP",
    25: "S_L4_V",
    26: "S_L5_A",
    27: "S_L5_LP",
    28: "S_L5_SP",
    29: "S_L5_V",
    30: "S_LPOE",
    31: "S_LPOW"
}
