"""Physical constants used in the project"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_constants.ipynb.

# %% auto 0
__all__ = ['MU_BY_SYSTEM', 'EM_MU', 'EM_POINTS', 'family_classification', 'ORBIT_FAMILIES', 'extended_orbit_classification',
           'EXTENDED_ORBIT_CLASSIFICATION']

# %% ../nbs/00_constants.ipynb 2
import pandas as pd

# %% ../nbs/00_constants.ipynb 4
MU_BY_SYSTEM = {'SaE': 1.901109735892602e-07,
                'MP': 1.611081404409632e-08,
                'SaT': 0.0002366393158331484,
                'EM': 0.01215058560962404,
                'JE': 2.52801752854e-05,
                'SE': 3.0542e-06,
                'SM': 3.227154996101724e-07}

# %% ../nbs/00_constants.ipynb 6
EM_MU = MU_BY_SYSTEM['EM']

EM_POINTS = {
    'Moon': (1-EM_MU,0,0),
    'Earth': (-EM_MU,0,0),
    'Lagrange 1': (0.8369,0,0),
    'Lagrange 2': (1.1557,0,0),
    'Lagrange 3': (-1.0051,0,0),
    'Lagrange 4': (0.4879,0.8660,0),
    'Lagrange 5': (0.4879,-0.8660,0)
}

# %% ../nbs/00_constants.ipynb 10
family_classification = {
    "Id": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42],
    "Label": ["S_BN", "S_BS", "S_DN", "S_DPO", "S_DRO", "S_DS", "S_L1_A", "S_L1_HN", "S_L1_HS", "S_L1_L", "S_L1_V", "S_L2_A", "S_L2_HN", "S_L2_HS", "S_L2_L", "S_L2_V", "S_L3_A", "S_L3_HN", "S_L3_HS", "S_L3_L", "S_L3_V", "S_L4_A", "S_L4_LP", "S_L4_SP", "S_L4_V", "S_L5_A", "S_L5_LP", "S_L5_SP", "S_L5_V", "S_LPOE", "S_LPOW", "S_R11", "S_R12", "S_R13", "S_R14", "S_R21", "S_R23", "S_R31", "S_R32", "S_R34", "S_R41", "S_R43"]
}

ORBIT_FAMILIES = pd.DataFrame(family_classification)

# %% ../nbs/00_constants.ipynb 14
extended_orbit_classification = {
    "Id": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42],
    "Label": ["S_BN", "S_BS", "S_DN", "S_DPO", "S_DRO", "S_DS", "S_L1_A", "S_L1_HN", "S_L1_HS", "S_L1_L", "S_L1_V", "S_L2_A", "S_L2_HN", "S_L2_HS", "S_L2_L", "S_L2_V", "S_L3_A", "S_L3_HN", "S_L3_HS", "S_L3_L", "S_L3_V", "S_L4_A", "S_L4_LP", "S_L4_SP", "S_L4_V", "S_L5_A", "S_L5_LP", "S_L5_SP", "S_L5_V", "S_LPOE", "S_LPOW", "S_R11", "S_R12", "S_R13", "S_R14", "S_R21", "S_R23", "S_R31", "S_R32", "S_R34", "S_R41", "S_R43"],
    "Type": ["System-wide", "System-wide", "System-wide", "System-wide", "System-wide", "System-wide", "L1", "L1", "L1", "L1", "L1", "L2", "L2", "L2", "L2", "L2", "L3", "L3", "L3", "L3", "L3", "L4", "L4", "L4", "L4", "L5", "L5", "L5", "L5", "System-wide", "System-wide", "Resonant", "Resonant", "Resonant", "Resonant", "Resonant", "Resonant", "Resonant", "Resonant", "Resonant", "Resonant", "Resonant"],
    "Subtype": ["Butterfly", "Butterfly", "Dragonfly", "Distant Prograde", "Distant Retrograde", "Dragonfly", "Axial", "Halo", "Halo", "Lyapunov", "Vertical", "Axial", "Halo", "Halo", "Lyapunov", "Vertical", "Axial", "Halo", "Halo", "Lyapunov", "Vertical", "Axial", "Long Period", "Short Period", "Vertical", "Axial", "Long Period", "Short Period", "Vertical", "Low Prograde", "Low Prograde", "Resonant 1,1", "Resonant 1,2", "Resonant 1,3", "Resonant 1,4", "Resonant 2,1", "Resonant 2,3", "Resonant 3,1", "Resonant 3,2", "Resonant 3,4", "Resonant 4,1", "Resonant 4,3"],
    "Direction": ["North", "South", "North", "Planar", "Planar", "South", "No specification", "North", "South", "Planar", "No specification", "No specification", "North", "South", "Planar", "No specification", "No specification", "North", "South", "Planar", "No specification", "No specification", "No specification", "No specification", "No specification", "No specification", "No specification", "No specification", "No specification", "East", "West", "Planar", "Planar", "Planar", "Planar", "Planar", "Planar", "Planar", "Planar", "Planar", "Planar", "Planar"]
}

EXTENDED_ORBIT_CLASSIFICATION = pd.DataFrame(extended_orbit_classification)
