# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/06_model.ipynb.

# %% auto 0
__all__ = ['get_optimizer']

# %% ../nbs/06_model.ipynb 2
from tensorflow.keras.optimizers import Adam, SGD

# %% ../nbs/06_model.ipynb 3
def get_optimizer(optimizer_config):
    name = optimizer_config['name'].lower()
    if name == 'adam':
        return Adam(learning_rate=optimizer_config.get('learning_rate', 0.001))
    elif name == 'sgd':
        return SGD(learning_rate=optimizer_config.get('learning_rate', 0.01))
    # Add additional optimizers as needed
    raise ValueError("Unsupported optimizer: {}".format(optimizer_config['name']))
